### ISSUE TITLE
Is it possible to use this with plugins?

### ISSUE THREAD

**Issue by GunterO** [EvzenP/STraSAK#3]
Hello. No issue, but a question. Can I use your toolkit in combination with a Trados Studio plugin? Specifically for the StarTransit plugin to import PPF files? This plugin creates a Ribbon button to do the import. 
Thanks for your time!

**Comment by EvzenP** [comment]
Hi Gunter,
I'm afraid that today's Paul Filkin's answer in SDL forums is the answer:

![image](https://user-images.githubusercontent.com/14029033/92159376-93de9b80-ee2d-11ea-871a-bbd334b39467.png)
